POST http://localhost:9000/test
Content-Type:  application/json 

{
  "payload" : {"someNum":123, "name":"fred"}
} 

###

GET http://localhost:9000/test2

###



GET https://test-lcarbonaro.netlify.com/.netlify/functions/test2

###

POST https://test-lcarbonaro.netlify.com/.netlify/functions/test
Content-Type:  application/json 

{
  "payload" : [{"id":123, "name":"fred"}, {"id":456, "name":"jo"}]
} 